version: '3.8'
services:
    mysql:
        image: 'mysql:8.0'
        container_name: mysql-laravel
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
            MYSQL_DATABASE: '${MYSQL_DATABASE}'
            MYSQL_USER: '${MYSQL_USER}'
            MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
        ports:
            - '3306:3306'
        volumes:
            - 'db_data:/var/lib/mysql'
        networks:
            - laravel-network
volumes:
    db_data: null
    sail-mysql:
        driver: local
networks:
    laravel-network:
        driver: bridge
